### ISSUE TITLE
@storybook/react has no member addDecorator

### ISSUE THREAD

**Issue by sw-tracker** [bitttttten/storybook-mock-date-decorator#1]
Hi there,

In you documentation, it says to import the react decorator: `import { addDecorator } from '@storybook/react';`. I get the error `@storybook/react has no member addDecorator`. I am on storybook version 7.

Thanks!

**Comment by alixlahuec** [comment]
Looks like `addDecorator` was removed in Storybook 7: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#removed-global-client-apis

> The addParameters and addDecorator APIs to add global decorators and parameters, exported by the various frameworks (e.g. @storybook/react) and @storybook/client were deprecated in 6.0 and have been removed in 7.0.
Instead, use `export const parameters = {};` and `export const decorators = [];` in your `.storybook/preview.js`. Addon authors similarly should use such an export in a preview entry file (see [Preview entries](https://github.com/storybookjs/storybook/blob/next/docs/addons/writing-presets.md#preview-entries)).

**Comment by bitttttten** [comment]
Ahh yes, I've just updated the docs in this package since they were only referencing the v6 API 👻 

Thanks @alixlahuec 🖖
