### ISSUE TITLE
Depends on old version of @storybook/addons

### ISSUE THREAD

**Issue by dominics** [bitttttten/storybook-mock-date-decorator#3]
https://github.com/bitttttten/storybook-mock-date-decorator/blob/33066fedc366f914ff760f61b0c47063422624da/package.json#L14

While attempting an upgrade to Storybook 7.x, the automigrate/upgrade helper complains:

```
││   Critical: The following dependencies are duplicated and WILL cause unexpected behavior:                                                  
││ 
││   @storybook/core-events:                                                                                                                   
││   7.6.9, 6.5.16                                                                                                                             
||                                                                                                                                   
││   Attention: The following dependencies are duplicated which might cause unexpected behavior:                                               
││                                                                                                                                            
││   @storybook/channels:                                                                                                                      
││   7.6.9, 6.5.16
```

Running `yarn why` indicates this is because of the dependency in this package:

```
=> Found "@storybook/addons#@storybook/core-events@6.5.16"
info This module exists because "_project_#project-name#storybook-mock-date-decorator#@storybook#addons" depends on it.

=> Found "@storybook/addons#@storybook/channels@6.5.16"
info This module exists because "_project_#project-name#storybook-mock-date-decorator#@storybook#addons" depends on it.
```

Maybe it should instead be a peer-dependency?

**Comment by david-morris** [comment]
This is also a problem for me.  This major version change does actually matter, since `makeDecorator` is exported from a different package in storybook 7.

Specifically, both `makeDecorator` and `MakeDecoratorResult` are exported from `@storybook/preview-api`.

**Comment by bitttttten** [comment]
gotcha okay. npm dependencies were a bit of a mystery back then for me. @david-morris @dominics i'll add it as a peer dependency and publish it on the weekend when i am back at my laptop 🤙

**Comment by Adrii77** [comment]
Same problem here ! : /

**Comment by fernandopasik** [comment]
@bitttttten I've contributed a PR to solve this issue, let me know if you are happy with it

**Comment by bitttttten** [comment]
thank you! i will aim to merge it in the morning:)

**Comment by bitttttten** [comment]
hey all, please try v1.0.2 🙏 

looks fixed from here! lmk if not
