### ISSUE TITLE
Incorrect export name in decorator.js

### ISSUE THREAD

**Issue by jipis** [bitttttten/storybook-mock-date-decorator#9]
index.js tries to `import { decorator } from "./decorator";`

but in decorator.js, `export const generator = ...`

Which is probably why 2.0.1 crashes and burns when you try to run a story using it.

**Comment by bitttttten** [comment]
Oops indeed, I didn't commit my latest changes 😅 
(that's me not testing after publish, only testing my locally linked package)

**Comment by bitttttten** [comment]
Published 2.0.2. Testing locally now :)

**Comment by bitttttten** [comment]
Okay looks fixed from here. Let me know if you run into trouble.

**Comment by bitttttten** [comment]
Published 2.0.5 which also updates the types too.

![Screenshot 2024-07-17 at 16 40 28](https://github.com/user-attachments/assets/5467d2db-d28c-4ca3-8210-385dcd355502)
![Screenshot 2024-07-17 at 16 40 33](https://github.com/user-attachments/assets/a294907c-9377-41fa-94e9-abf5033d3743)
